NumPy Lab
Alex Weinberg

# Question 1

In [1]:
import numpy as np

A = np.array( [ [3, -1, 4 ],[1, 5 ,-9] ])
B = np.array( [ [2, 6, -5, 3],[5, -8, 9, 7], [9, -3, -2, -3]] )

np.dot(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

# Question 2

In [7]:
A = np.array([ [3, 1, 4], [ 1, 5, 9], [-5, 3, 1] ])
a2 = np.dot(A,A)

result = (-1) * (np.dot(a2,A)) + 9*(np.dot(A,A)) - 15*A
result

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Question 3

In [22]:
aux = np.ones( (7,7))
A = np.triu(A)

aux2 = -1 * np.ones( (7,7))
aux3 = 5 * np.ones( (7,7))

B = np.tril(aux2) + np.triu(aux3) + ((-5) * np.eye(7) )

result = A @ B @ A
result = result.astype(np.int64)

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

# Question 4

In [24]:
def problem4(arr):
    
    copy_arr = np.copy(arr)
    neg_index = copy_arr < 0
    
    copy_arr[neg_index] = 0
    return copy_arr

test = np.array([5, -5, 4])
problem4(test)

array([5, 0, 4])

# Question 5

In [75]:
A = np.arange(6).reshape((3,2)).T
B = np.tril( (3 * np.ones((3,3)) ))
C = (-2) * np.eye(3)

I = np.eye(3)

row1 = np.column_stack((np.zeros_like(I), A.T, I))
row2 = np.hstack((A, np.zeros((2,2)) , np.zeros_like(A)))
row3 = np.hstack( (B, np.zeros_like(A.T), C))

result = np.vstack((row1, row2, row3))
result 

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0., -0., -0., -2.]])

# Question 6

In [105]:
def prob6(mat):
    
    i,j = np.shape(mat)
    sums = mat.sum(axis=1).reshape((j,1))
    result = mat / sums
    
    return result

test = np.arange(9).reshape((3,3))
prob6(test)


array([[0.        , 0.33333333, 0.66666667],
       [0.25      , 0.33333333, 0.41666667],
       [0.28571429, 0.33333333, 0.38095238]])

# Question 7
This is hard, come back to

In [2]:
def p7():
    grid=np.load('/Users/alexweinberg/Desktop/BootCamp2018/ProbSets/Comp/Week1/grid.npy')
    hmax= np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    vmax= np.max(grid[:-3,:] * grid[1:-2, :] * grid[2:-1, :] * grid[3:,:])
    drmax= np.max(grid[:-3, :-3]*grid[1:-2, 1:-2]*grid[2:-1, 2:-1]*grid[3:, 3:])
    lrmax= np.max(grid[3:, :-3]*grid[2:-1, 1:-2]*grid[1:-2, 2:-1]*grid[:-3, 3:])
    print(hmax)
    print(vmax)
    print(drmax)
    print(lrmax)
    return
# copied from tim 